package Values;

public class Values {
    public static int
            MAP_HEIGHT = 20,
            MAP_WIDTH = 20,
            INITIAL_MONEY = 10,
            WORK_SHOP_MAX_LEVEL = 4,
            CHICKEN_PRODUCT_TIME = 20,
            COW_PRODUCT_TIME = 20,
            SHEEP_PRODUCT_TIME = 20,
            TURKEY_PRODUCT_TIME = 20,
            CHICKEN_COST = 100,
            COW_COST = 1000,
            SHEEP_COST = 10000,
            TURKEY_COST = 100,
            CAT_COST = 1000,
            DOG_COST = 2000,
            LION_HEALTH = 5,
            BEAR_HEALTH = 5,
            GRASS_LIFE_TIME = 30,
            GRASS_VALUE = 10,
            CAT_SPEED = 38,
            LION_SPEED = 35,
            BEAR_SPEED = 29,
            COW_HEALTH = 40,
            SHEEP_HEALTH = 40,
            CHICKEN_HEALTH = 15,
            TURKEY_HEALTH = 15,
            COW_SPEED = 40,
            SHEEP_SPEED = 55,
            TURKEY_SPEED = 45,
            CHICKEN_SPEED = 60,
            DOG_SPEED = 65;
}
